### ISSUE TITLE
issue with pip install (python2)

### ISSUE THREAD

**Issue by rbeucher** [matplotlib/cmocean#70] opened 2018-07-18 21:47 UTC
Hi,

Pip install fails for python2 install because of missing Readme file:

```python
long_description=open('README.md').read(),
```

```bash
sudo pip2 install cmocean
Collecting cmocean
  Downloading https://files.pythonhosted.org/packages/0a/da/302ed3bb245833042961138521e4fa3cb9670aef40d90f32a9a1da83e7a5/cmocean-1.2.tar.gz (260kB)
    100% |████████████████████████████████| 266kB 2.5MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-kSlGW9/cmocean/setup.py", line 35, in <module>
        long_description=open('README.md').read(),
    IOError: [Errno 2] No such file or directory: 'README.md'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-kSlGW9/cmocean/
```

**Comment by tacaswell** [comment] 2018-07-19 00:39
Ah, the issue is https://github.com/matplotlib/cmocean/blob/7bf45bf490757ec24d2fb880b4c26ed9d161d3f5/MANIFEST.in#L1

which is the wrong file!

@kthyng we probably need to fix that and then do a micro release to fix it.

Building a python2 wheel (I was confused and thought it made universal wheels by default) and uploading that is a short-term work around.  There is a python3 wheel up which is why this worked when I tested it at scipy

@rbeucher Updating to python3 would also work around this problem.

**Comment by rbeucher** [comment] 2018-07-19 00:42
@tacaswell 

Yes I think the pb comes from the python2 wheel. Python3 is fine. My pb is that we cmocean is used as a dependency in our code and we have not fully transitioned to python2. I can pull the github repo for now and fix this.

**Comment by tacaswell** [comment] 2018-07-19 17:58
There is not a py2 wheel, you are getting the tarball instead (which is where the file is missing).

**Comment by kkozarev** [comment] 2018-08-14 12:46
Hi, I am having the same issue. Has a fix been implemented for this, or can you suggest a way to circumvent it?

**Comment by rbeucher** [comment] 2018-08-14 20:44
Hi @kkozarev

You can pull the sources from github and do a pip install on it.

**Comment by kthyng** [comment] 2019-01-11 19:34
I have changed from .rst to .md so hopefully this isn't an issue anymore. I will close this but feel free to comment if there is still a problem.

**Closed by kthyng** 2019-01-11 19:34 UTC
